### ISSUE TITLE
[Dungeon][Strat] Stratholme Main Gate - list of bugs

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#179]
- Missing all the quest givers from the beginning of the dungeon. They did appear at Balnarraz after killing him (as they should, to delived the quests).
https://www.youtube.com/watch?v=9OIcBvC7orw&t=20s
- Risen Hammersmith was summoned twice when using the scroll on the floor. Other one did disappear after 30-60sec though (was googling some stuff). Also they were both neutral, I'm not sure if they should attack you in Cata (they do attack in WotLK at least).
![WoWScrnShot_061722_131324](https://user-images.githubusercontent.com/43609330/174287135-2b903c1a-6c2a-4f1c-9f31-5bc9eaaa9871.jpg)
- Using cannon should kill the adds that keep getting summoned when engaging Willey Hopebreaker. Currently they do very little damage and don't even always hit them.
- Heartsinger Forresten only used melee attacks and Enchanting Lullaby against me. He should be using some kind of shot, I think multishot.

**Comment by ghost** [comment]
Fixed.

**Comment by MrTide** [comment]
Some of the issues still not fixed
More details here
https://github.com/SallyWhitemane/Maelstrom/issues/560
