### ISSUE TITLE
[Quest]  The Blackmaw Doublecross

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#356]
**Description:** This quest is offered to the players in azshara

**How to reproduce:** some dialogs are missing Ungarl wont greet you , Haggrum bloodfist dialogs/texts are missing both on the character and event, quest itself is doable but requires improvements 
![image](https://user-images.githubusercontent.com/36106057/175649120-25bd0390-8d0e-419b-8614-c3d93d522857.png)

**How it should work:** Like the video below
https://www.youtube.com/watch?v=dFPCsSUgqxQ

**Comment by Afgann** [comment]
fixed

**Comment by MrTide** [comment]
Thanks @Afgann he is still missing dialog tho
![image](https://user-images.githubusercontent.com/36106057/177422727-a887c170-3aad-46e2-bbec-45f3da031f52.png)
