### ISSUE TITLE
[NPC] Foe Reaper 5000 now has skinning flag after killed

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#77]
**Description:**
Title says it all, after killing Foe Reaper 5000 in Deadmines it now had skinning flag even its mechanical npc or something. There was some issue fixed with Young Panthers having skinning flag even when alive, dunno if this has anything to do with that, probably not.

**Comment by Afgann** [comment]
fixed

**Comment by phonkala** [comment]
Problem still exists (maybe after latest fixes to Deadmines).
